### ISSUE TITLE
Plotting issue

### ISSUE THREAD

**Issue by bozbezbozzel** [friendsofstrandseq/pipeline#12]
This line: https://github.com/friendsofstrandseq/mosaicatcher/blob/bef79615bccf44738e02756104ae48226da8a63e/R/qc.R#L66 is causing trouble for me. The 'w' column doesn't pass the integer check because it becomes a float after normalization (and so does c).

**Comment by meiers** [comment]
Should be fixed in the mosaicatcher develop version: https://github.com/friendsofstrandseq/mosaicatcher/commit/9b5231fdf1796520a3495bf6b3d2e0faa74748b5
