### ISSUE TITLE
Missing VCF file for unphaseable chromosomes

### ISSUE THREAD

**Issue by bozbezbozzel** [friendsofstrandseq/pipeline#14]
Snakemake stops the pipeline if a chromosome cannot phased due to line [600](https://github.com/friendsofstrandseq/pipeline/blob/6af66f000a711b33ac70961b88b93f7a2e7d06ec/Snakefile#L600). The line above causes no trouble because StrandPhaseR creates a phased_haps.txt regardless of whetehr a chromosome was phased or not, but it doesn't do the same for the VCF.

**Comment by daewoooo** [comment]
I think this issue should now be solved. Please test and let me know if this issue remains.

**Comment by bozbezbozzel** [comment]
Hi David,

I ran the pipeline again (from rule install_StrandPhaseR) so that the
newest version would get installed. Unfortunately I still got the same
error, and no VCF was created.
Was there another way I should've reinstalled StrandPhaseR?

Best,

Alex

**Comment by daewoooo** [comment]
Hi Alex,

I have made another fix to deal with this problem.
Please reinstall StrandPhaseR and run the pipeline again.

David

**Comment by tobiasmarschall** [comment]
I could reproduce the error and indeed with David's latest fix it worked. Also, note that I just made a new release of WhatsHap (0.17) that integrates a fix Jana made to the haplotagging command. This is required when chromosomes are missing in the VCF. I just updated the conda environment (commit 98d6a27) to use this new version. So before re-trying, make sure to update your environment.
